services:
  database:
    image: mariadb:10.11
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-app}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-!ChangeMe!}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-!ChangeMe!}
      MYSQL_USER: ${MYSQL_USER:-app}
    volumes:
      - database_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    environment:
      PMA_HOST: database
      PMA_USER: ${MYSQL_USER:-app}
      PMA_PASSWORD: ${MYSQL_PASSWORD:-!ChangeMe!}
    ports:
      - "8080:80"
    depends_on:
      - database

volumes:
  database_data:
